name: house_wallet
description: A new Flutter project. #TODO description

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true

# TODO icon
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  image_path_ios: assets/icon/icon_ios.png
  adaptive_icon_foreground: assets/icon/adaptive_foreground.png
  adaptive_icon_background: "#FFFFFF"

# TODO splash screen
# flutter pub run flutter_native_splash:create
# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/splash_screen.png