name: house_wallet
description: A new Flutter project. #TODO description

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_series: ^0.1.2
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  shared_preferences: ^2.1.1
  intl: ^0.18.0
  email_validator: ^2.1.17
  keyboard_dismisser: ^3.0.0
  font_awesome_flutter: ^10.4.0
  share_plus: ^7.0.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  image_picker: ^0.8.7+5
  shimmer: ^3.0.0
  firebase_storage: ^11.2.1
  provider: ^6.0.5
  badges: ^3.1.1
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true
  generate: true
  assets: [ assets/ ]

# TODO icon
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  image_path_ios: assets/icon/icon_ios.png
  adaptive_icon_foreground: assets/icon/adaptive_foreground.png
  adaptive_icon_background: "#FFFFFF"

# TODO splash screen
# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_screen.png